import Head from "next/head";
// import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import ImageGallery from "../components/ImageGallery/index"
import { fetchAPI } from "../lib/api";

// const currencies = ["CAD", "USD", "GBP", "AAA", "DDD", "EEE"];

export default function Home({albums}) {
  // console.log(albums)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {/* <ul>
          {currencies.map((currency) => (
            <li key={currency}>
              <Link
                href={`GalleryView/[GalleryView]?GalleryView=${currency}`}
                as={`/currency/${currency}`}
              >
                <a>{currency}</a>
              </Link>
            </li>
          ))}
        </ul> */}
        <ImageGallery albums={albums} />
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const qs = require('qs');

  const query = qs.stringify({
    fields: ['name', 'sub_title', 'slug' ],
    populate: {
      // images: {
      //   fields: ['name', 'url'],
      // },
      cover_image: {
        fields: ['name', 'url'],
      },
      // defaultCredits: {
      //   fields: ['credit_type', 'credit_value'],
      // },
    },
    // populate: '*', 
  }, {
    encodeValuesOnly: true,
  });

  // Run API calls in parallel
  const [albumsRes] = await Promise.all([
    fetchAPI(`/albums?${query}`),
  ])

  return {
    props: {
      albums: albumsRes.data,
    },
    revalidate: 1,
  }
}
